title: Sr
author: Fabricio Pedro
email: wolfxzero2@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This web site discuss java, javascript and frameworks web. Welcome to my site.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
